language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qtbase5-dev libz-dev zlib1g-dev liblz-dev libbz2-dev libarchive-dev xdg-utils libpoppler-qt5-dev libqt5scintilla2-dev libdjvulibre-dev libqt5webkit5-dev

script:
  - qmake -qt5 CONFIG+=release PREFIX=/usr
  - make -j$(nproc)
  - make INSTALL_ROOT=appdir -j$(nproc) install

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
